---

- name: Ensure lookup required environment variables
  ansible.builtin.set_fact: { "{{ item }}": "{{ lookup('env', item | upper ) }}" }
  loop: "{{ set_and_check_facts_from_environment_required_vars }}"
  
- name: Check required environment variables
  ansible.builtin.fail:
    msg: Environment variable '{{ item }}' is not set
  when: not lookup('vars', item)
  with_items: "{{ set_and_check_facts_from_environment_required_vars }}"

...